name: compiled-minicourse
channels:
  - conda-forge
dependencies:
  - python >=3.8
  - numpy >=1.18
  - matplotlib >=3
  - scipy >=1.2
  - jupyterlab >=2
  - plumbum >=1.6.9
  - numba >=0.49
  - pybind11 >=2.5
  - cython >=0.29.17
  - swig >=4
  - cppyy >=1.6
  - cffi >=1.14
  - compilers
  - cmake